name: Update copyright year in license file

on:
  schedule:
    - cron: '0 0 1 1 *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v2

      - name: Update license year
        uses: p3lim/license-year-updater@v1
        with:
          files: LICENSE

      - name: Apply changes
        uses: swinton/commit@v2.0.0
        with:
         # Newline-separated list of files to be committed, relative to root of repository.
         files: LICENSE
         # Commit message to be used
         commit-message: Happy new year
