name: Update copyright year in license file

on:
  schedule:
    - cron: '0 0 1 1 *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v2

      - name: Update license year
        uses: p3lim/license-year-updater@v1
        with:
          files: LICENSE
      - name: Simple commit
        uses: zwaldowski/git-commit-action@v1
        with:
          # Directory to create commit in
          working_directory: $GITHUB_WORKSPACE # optional, default is .
          # Commit message
          commit_message: Update license year # default is Automated commit
          # Name to use for commit author
          author_name: Automated license updater # optional, default is GitHub Actions
